name:                MigrateCLI
version:             0.1.0.0
github:              "Arraying/MigrateCLI"
license:             BSD-3-Clause
author:              "Paul Hübner"
maintainer:          "paul.huebner@googlemail.com"
copyright:           "2023 Paul Hübner"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Arraying/MigrateCLI#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3 && < 1.4
- dotenv >= 0.11 && < 0.12
- filepath >= 1.4 && < 1.5
- optparse-applicative >= 0.17
- time >= 1.12 && < 1.13

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  MigrateCLI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MigrateCLI

tests:
  MigrateCLI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MigrateCLI
